MeetingApp/Models/MeetingInfo.cs
namespace MeetingApp.Models
{
    public class MeetingInfo()
    {
        public int Id { get; set; }
        public string? location { get; set; }
        public DateTime date { get; set; }

        public int numberofpeople { get; set; }
    }
    
}

MeetingApp/Models/Repository.cs
namespace MeetingApp.Models
{
    public static class Repository
    {
        private static List<UserInfo> _users = new();

        static Repository ()
         {
            _users.Add(new UserInfo() {Id=1,Name="Zeynep",Email="abc@gmail.com",Phone="23244",WillAttend=true});

            _users.Add(new UserInfo() {Id=2,Name="Ozan",Email="ozan@gmail.com",Phone="32488",WillAttend=false});

            _users.Add(new UserInfo() {Id=3,Name="Ali",Email="ali@gmail.com",Phone="54657",WillAttend=true});

            

        }


        public static List<UserInfo> Users{
            get{
                return _users;
            }
        }

        public static void CreateUser(UserInfo user)
        {
            user.Id = Users.Count + 1;
             _users.Add(user);
        }

        public static UserInfo? GetById(int id)
        {
            return _users.FirstOrDefault(user => user.Id == id);
        }
    }
}

MeetingApp/Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models
{
        public class UserInfo
        {
            public int Id { get; set; }

            [Required]
            public string? Name { get; set; }

            [Required]
            public string? Phone { get; set; }

            [Required]
            [EmailAddress]
            public string? Email  { get; set; }

            [Required]
            public bool WillAttend { get; set; }
        }
}

MeetingApp/Controllers/HomeController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers {
    public class HomeController : Controller {
        public IActionResult Index(){
            int saat = DateTime.Now.Hour;
            

            ViewBag.Selamlama = saat > 12 ? "İyi günler" : "Günaydın";
            int usercount = Repository.Users.Where(i=>i.WillAttend == true).Count();

            //ViewBag.userName = "Ozan";

            var meetinginfo = new MeetingInfo(){
                Id = 1,
                location = "Eskişehir , Merkez",
                date = new DateTime(2025,02,6,20 ,0 , 0),
                numberofpeople = usercount
            };

            return View(meetinginfo);
        }
    }
}

MeetingApp/Controllers/MeetingController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    
    public class MeetingController : Controller
    {
        

        [HttpGet]
        public IActionResult Apply(){
            return View();
        }
        [HttpPost]
        public IActionResult Apply(UserInfo model){

            if(ModelState.IsValid)
            {
                Repository.CreateUser(model);
            ViewBag.UserCount = Repository.Users.Where(i=>i.WillAttend == true).Count();
            return View("Thanks",model);
            }
            else{
                return View(model); 
            }

            
        }

        public IActionResult List()
        {
            return View(Repository.Users);
        }

        //meeting/details/2 -- örnek 
        public IActionResult Details(int id)
        {
            return View(Repository.GetById(id));
        }
    }
}

MeetingApp/Views/Home/index.cshtml
@model MeetingInfo;
@{
    ViewBag.Title = "Toplantı Başvuru";
    Layout = "_Layout2";
}
<main class="text-center">
<h1 class="h4">@ViewBag.Selamlama</h1>
<p>toplantı katılım durumunuzu bildiriniz.</p>

<div class="card my-2">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">@Model.location</li>
        <li class="list-group-item">@Model.date.ToString("dd/MM/yyyy HH:mm:ss") tarihinde gerçekleşecek.</li>
        <li class="list-group-item">@Model.numberofpeople Katılımcı</li>

    </ul>
</div>

<a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">başvuru yap</a>
</main>

MeetingApp/Views/Meeting/Apply.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Formu";
}

<h1 class="h4" text-center>Toplantı katılım formu</h1>

<form method="post" action="/Meeting/Apply" novalidate>
    <div asp-validation-summary="All">

    </div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">İsim</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Telefon</label>
        <input asp-for="Phone" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">Katılım Durumu</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="">Seçiniz</option>
            <option value="true">Evet , Geliyorum</option>
            <option value="false">Hayır , Gelmiyorum</option>
        </select>
    </div>

    <button class="btn btn-primary" type="submit">Kaydet</button>
</form>

MeetingApp/Views/Meeting/Details.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Detayı";
}

@{
    var className = @Model.WillAttend == true  ? "primary" : "danger";
}

<main class="text-center">
    <h1 class="h4">Başvuru Detayı</h1>
    <p>
        <span class="badge text-bg-@className">
            @if(Model.WillAttend == true){
                <text>Katılıyor</text>
            }
            else{
                <text>Katılmıyor</text>
            }
        </span>
    </p>
    <p>İsim : @Model.Name</p>
    <p>Email : @Model.Email</p>
    <p>Telefon : @Model.Phone</p>
    <a asp-controller="Meeting" asp-action="List" class="btn btn-outline-@className">Katılımcı Listesi</a>
</main>

MeetingApp/Views/Meeting/List.cshtml
@model List<UserInfo>
@{
    ViewBag.Title = "Toplantı Katılım Listesi";
}
<main class="text-center">
<h1 class="h4">Toplantıya Katılım Listesi</h1>

<table class="table table-border">
    <thead>
        <tr>
            <td>ad</td>
            <td>katılım durumu</td>
            <td>Detay</td>
        </tr>
    </thead>

    <tbody>
        @{int i = 0;}
         @foreach(var user in Model)
         {

        var durum = user.WillAttend == true ? "Evet" : "Hayır";
        var classname = user.WillAttend == true ? "table-success" : "table-danger";

        if(user.WillAttend == true) {
            i++;
        }
         
        <tr class="@classname">
            <td>@user.Name</td>
            <td>@durum</td>
            <td>
                <a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a>
            </td>
        </tr>
        }
    </tbody>
</table>
    <div class="card">
        <div class="card-body">
            <span>Katılımcı Sayısı : @i</span>
        </div>
    </div>
</main>

MeetingApp/Views/Meeting/Thanks.cshtml
@model UserInfo 
@{
    ViewBag.Title = "Başvuru Durumu";
}
<main class="text-center">
<h1 class="h4">Başvuru Durumu</h1>


@if(Model.WillAttend == true)
{
    <p>Teşekkürler , @Model.Name toplantıya sizinle birlikte @ViewBag.UserCount kişi katıldı.</p>

    <a class="btn btn-sm btn-outline-primary" href="/Meeting/list">katılımcıları listele</a>
}
else{
    <p>@Model.Name , katılmadığından dolayı üzgünüz.
    </p>
    <a class="btn btn-sm btn-outline-primary" href="/meeting/apply">Başvuru Formu</a>
}

</main>

MeetingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-primary text-white p-2 text-center">
        Meeting App
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto ">
                <div class="card">
                <div class="card-body">
                    @RenderBody()
                    </div>
                </div>
            </div>
        </div>
</div>
    
</body>
</html>

MeetingApp/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-danger text-white p-2 text-center">
        Meeting App
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card">
                <div class="card-body">
                    @RenderBody()
                    </div>
                </div>
            </div>
        </div>
</div>
    
</body>
</html>